#!/usr/bin/env python3


import numpy
import pandas
# import pyarrow
import scipy


print(f'NumPy {numpy.__version__}')
print(f'Pandas {pandas.__version__}')
# print(f'PyArrow {pyarrow.__version__}')
print(f'SciPy {scipy.__version__}')
