#!/usr/bin/env bash


python3 -m pip install --upgrade PIP SetUpTools --user

python3.9 -m pip install --upgrade PIP SetUpTools --user
python3.8 -m pip install --upgrade PIP SetUpTools --user
python3.7 -m pip install --upgrade PIP SetUpTools --user
