#!/usr/bin/env bash


# ref: https://github.com/apache/arrow/blob/master/docs/source/developers/cpp/building.rst


sudo apt upgrade --yes cmake ninja-build

cd /tmp
git clone https://GitHub.com/Apache/Arrow
cd Arrow/cpp
mkdir release
cd release
cmake ..
ninja
make install
